
name: shareeat

services:
  db:
    image: postgres:14
    container_name: shareeat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shareeat_db
      - POSTGRES_USER=shafiullahshafin
      - POSTGRES_PASSWORD=EmptyAs0!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shafiullahshafin -d shareeat_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shareeat_network

  web:
    build: ./backend
    container_name: shareeat_web
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn shareeat.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - shareeat_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shareeat_frontend
    volumes:
      - frontend_build:/usr/share/nginx/html

  nginx:
    image: nginx:alpine
    container_name: shareeat_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - frontend_build:/usr/share/nginx/html
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
      - frontend
    networks:
      - shareeat_network

volumes:
  postgres_data:
  static_volume:
  media_volume:
  frontend_build:

networks:
  shareeat_network:
    driver: bridge